[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/save-link"
  to = "/.netlify/functions/save-link"
  status = 200

[[redirects]]
  from = "/api/list-links"
  to = "/.netlify/functions/list-links"
  status = 200

[[redirects]]
  from = "/api/delete-link"
  to = "/.netlify/functions/delete-link"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/go/:splat"
  status = 302
